name: TwilightLib
version: '${project.version}'
main: net.twlghtdrgn.twilightlib.TwilightLib
api-version: '1.20'
authors: [TwlghtDrgn]
description: A library for TwlghtDrgn's plugins
website: https://github.com/TwlghtDrgn/TwilightLib
loader: net.twlghtdrgn.twilightlib.TwilightLibLoader
dependencies:
    server:
        MiniPlaceholders:
            load: BEFORE
            required: false